<?php

namespace Mix\Redis\Pool;

use \Mix\Pool\ConnectionPoolInterface;

/**
 * Class ConnectionPool
 * @author LIUJIAN <coder.keda@gmail.com>
 * @package Mix\Redis\Coroutine
 */
class ConnectionPool extends \Mix\Pool\ConnectionPool implements ConnectionPoolInterface
{

    /**
     * 获取连接
     * @return RedisConnection
     */
    public function getConnection()
    {
        return parent::getConnection(); // TODO: Change the autogenerated stub
    }

}
